"""
pixel_intensity_analysis.py — Pixel Intensity vs Error Rate Analysis
=====================================================================
Investigates whether image brightness and contrast correlate with
model misclassification rates for both EfficientNet-B4 and XceptionNet.

Motivation:
    Grad-CAM visualisations suggested that atypical illumination conditions
    (very dark, very bright, or high-contrast images) contribute to model
    failures. This script quantifies that relationship mathematically by
    computing pixel-level statistics for every test image and mapping them
    against model error flags.

Features computed per image:
    - mean_brightness: average pixel intensity across all channels (0-255)
      Computed using standard luminance formula: 0.299R + 0.587G + 0.114B
      Weights reflect human perceptual sensitivity to different wavelengths
    - std_brightness: standard deviation of pixel intensity
      Used as a proxy for image contrast (high std = high contrast)
    - mean_r, mean_g, mean_b: per-channel means
      Can reveal colour-cast biases (e.g. red-tinted images)

Error flags:
    - eff_error = 1 if EfficientNet prediction != ground truth label
    - xcp_error = 1 if XceptionNet prediction != ground truth label

Usage:
    python pixel_intensity_analysis.py

Prerequisites:
    - predictions_cache.csv must exist (generated by thesis_train.py)
      Contains: path, label, eff_pred, xcp_pred, eff_prob, xcp_prob

Outputs:
    - ~/results/pixel_intensity_results.csv — per-image pixel stats + error flags
      Use plot_pixel_intensity.py to visualise the results

Author: Wajeeha Khan
Institution: Tilburg University — MSc Data Science & Society 2026
"""

import csv
import os
import sys

# ─────────────────────────────────────────
# IMPORTS
# ─────────────────────────────────────────
# Lightweight dependencies — only PIL and numpy required
# This script was designed to run without a full conda/venv setup

try:
    from PIL import Image
    import numpy as np
except ImportError as e:
    print(f"Missing library: {e}")
    print("Install with: pip install Pillow numpy")
    sys.exit(1)

# ─────────────────────────────────────────
# PATHS
# ─────────────────────────────────────────
# predictions_cache.csv is generated by thesis_train.py during inference
# It contains one row per test image with model predictions and probabilities
PREDICTIONS_CSV = os.path.expanduser('~/results/predictions_cache.csv')
OUTPUT_CSV      = os.path.expanduser('~/results/pixel_intensity_results.csv')

os.makedirs(os.path.expanduser('~/results'), exist_ok=True)

# ─────────────────────────────────────────
# LOAD PREDICTIONS
# ─────────────────────────────────────────
print("Loading predictions cache...")

rows = []
with open(PREDICTIONS_CSV, 'r') as f:
    reader = csv.DictReader(f)
    for row in reader:
        rows.append(row)

print(f"Loaded {len(rows):,} rows. Processing images...")

# ─────────────────────────────────────────
# COMPUTE PIXEL STATISTICS
# ─────────────────────────────────────────

results        = []
errors_skipped = 0

for i, row in enumerate(rows):
    if i % 1000 == 0:
        print(f"  {i}/{len(rows)}...")

    path     = row['path']
    label    = int(row['label'])
    eff_pred = int(row['eff_pred'])
    xcp_pred = int(row['xcp_pred'])
    eff_prob = float(row['eff_prob'])
    xcp_prob = float(row['xcp_prob'])

    try:
        # Load and resize to standard 224x224 for consistent statistics
        img = Image.open(path).convert('RGB')
        img = img.resize((224, 224))
        arr = np.array(img, dtype=np.float32)  # shape: (224, 224, 3)

        # ── Brightness (luminance) ──
        # Standard ITU-R BT.601 luminance formula
        # Weights: R=0.299, G=0.587, B=0.114
        # Green weighted highest because human eye is most sensitive to green
        gray = 0.299 * arr[:,:,0] + 0.587 * arr[:,:,1] + 0.114 * arr[:,:,2]

        mean_brightness = float(np.mean(gray))   # overall image brightness (0-255)
        std_brightness  = float(np.std(gray))    # contrast proxy: high = high contrast

        # ── Per-channel means ──
        # Useful for detecting colour casts (e.g. red-tinted studio lighting)
        mean_r = float(np.mean(arr[:,:,0]))
        mean_g = float(np.mean(arr[:,:,1]))
        mean_b = float(np.mean(arr[:,:,2]))

        # ── Error flags ──
        # 1 = model made an error on this image, 0 = correct prediction
        eff_error = 1 if eff_pred != label else 0
        xcp_error = 1 if xcp_pred != label else 0

        results.append({
            'path':             path,
            'label':            label,
            'eff_pred':         eff_pred,
            'xcp_pred':         xcp_pred,
            'eff_prob':         eff_prob,
            'xcp_prob':         xcp_prob,
            'eff_error':        eff_error,
            'xcp_error':        xcp_error,
            'mean_brightness':  mean_brightness,
            'std_brightness':   std_brightness,
            'mean_r':           mean_r,
            'mean_g':           mean_g,
            'mean_b':           mean_b,
        })

    except Exception:
        # Skip unreadable images silently
        errors_skipped += 1
        continue

print(f"\nDone. Processed {len(results):,} images, skipped {errors_skipped}.")

# ─────────────────────────────────────────
# SAVE RESULTS
# ─────────────────────────────────────────
fieldnames = [
    'path', 'label', 'eff_pred', 'xcp_pred', 'eff_prob', 'xcp_prob',
    'eff_error', 'xcp_error', 'mean_brightness', 'std_brightness',
    'mean_r', 'mean_g', 'mean_b'
]

with open(OUTPUT_CSV, 'w', newline='') as f:
    writer = csv.DictWriter(f, fieldnames=fieldnames)
    writer.writeheader()
    writer.writerows(results)

print(f"Saved to {OUTPUT_CSV}")
print(f"Run plot_pixel_intensity.py to visualise the results.")
