"""
plot_histogram_final.py — Age Distribution Histogram
=====================================================
Visualises the age distribution of the test set, comparing real faces
(CelebA/FFHQ) against StyleGAN-generated fake faces.

Purpose:
    Understanding the demographic composition of the dataset is essential
    for interpreting bias findings. If StyleGAN generates more faces in
    certain age groups, models may have less training signal for others,
    contributing to higher error rates for underrepresented demographics.

Key finding:
    StyleGAN over-generates younger faces (Under 20: 317 fake vs 227 real)
    and under-generates older faces (50+: 153 fake vs 293 real). This
    imbalance partially explains why models show higher FNR for young faces.

Data source:
    demographics_cache.csv — generated by thesis_train.py using DeepFace
    to estimate age and gender for each test image. Ages are estimates,
    not ground truth (DeepFace MAE = 12.21 years on UTKFace validation).

Usage:
    python plot_histogram_final.py

Prerequisites:
    - ~/results/demographics_cache.csv must exist (from thesis_train.py)

Outputs:
    - ~/results/age_distribution_histogram.png

Author: Wajeeha Khan
Institution: Tilburg University — MSc Data Science & Society 2026
"""

import os
import numpy as np
import pandas as pd

import matplotlib
matplotlib.use('Agg')
import matplotlib.pyplot as plt

# ─────────────────────────────────────────
# PATHS
# ─────────────────────────────────────────
DEMO_CSV = os.path.expanduser('~/results/demographics_cache.csv')
OUTPUT   = os.path.expanduser('~/results/age_distribution_histogram.png')

os.makedirs(os.path.expanduser('~/results'), exist_ok=True)

# ─────────────────────────────────────────
# LOAD & PREPROCESS
# ─────────────────────────────────────────
df = pd.read_csv(DEMO_CSV)
df = df.dropna(subset=['age'])
df['age'] = df['age'].astype(int)

# Extract real/fake label from file path
# Path contains '/fake/' for StyleGAN images and '/real/' for real images
df['label'] = df['path'].apply(
    lambda p: 'Fake (StyleGAN)' if '/fake/' in p else 'Real'
)

# Assign age groups — same bins used throughout the thesis
def age_group(age):
    if age < 20:   return 'Under 20'
    elif age < 35: return '20-34'
    elif age < 50: return '35-49'
    else:          return '50+'

df['age_group'] = df['age'].apply(age_group)
order    = ['Under 20', '20-34', '35-49', '50+']

real_df = df[df['label'] == 'Real']
fake_df = df[df['label'] == 'Fake (StyleGAN)']

print(f"Real: {len(real_df):,} | Fake: {len(fake_df):,}")
print("\nAge group distribution:")
print(df.groupby(['label', 'age_group']).size().unstack(fill_value=0))

# ─────────────────────────────────────────
# PLOT
# ─────────────────────────────────────────
fig, axes = plt.subplots(1, 2, figsize=(14, 5))
fig.patch.set_facecolor('white')

# ── Panel 1: Raw age histogram (overlapping) ──
# Shows the full continuous age distribution with mean lines
axes[0].hist(real_df['age'], bins=40, color='#2a9d8f', alpha=0.7,
             label='Real', edgecolor='white')
axes[0].hist(fake_df['age'], bins=40, color='#e76f51', alpha=0.7,
             label='Fake (StyleGAN)', edgecolor='white')

# Mean age lines
axes[0].axvline(real_df['age'].mean(), color='#2a9d8f', lw=2, linestyle='--',
                label=f'Real mean = {real_df["age"].mean():.1f}')
axes[0].axvline(fake_df['age'].mean(), color='#e76f51', lw=2, linestyle='--',
                label=f'Fake mean = {fake_df["age"].mean():.1f}')

axes[0].set_xlabel('Age (estimated by DeepFace)', fontsize=12)
axes[0].set_ylabel('Count', fontsize=12)
axes[0].set_title('Age Distribution — Test Set (Real vs Fake)', fontsize=13, fontweight='bold')
axes[0].legend(fontsize=10)
axes[0].set_facecolor('#f9f9f9')

# ── Panel 2: Grouped bar chart by age group ──
# Shows counts per age group side by side for easy comparison
real_counts = real_df['age_group'].value_counts().reindex(order)
fake_counts = fake_df['age_group'].value_counts().reindex(order)

x     = np.arange(len(order))
width = 0.35

bars1 = axes[1].bar(x - width/2, real_counts.values, width,
                    color='#2a9d8f', alpha=0.85, label='Real')
bars2 = axes[1].bar(x + width/2, fake_counts.values, width,
                    color='#e76f51', alpha=0.85, label='Fake (StyleGAN)')

# Add count labels on top of each bar
for bar in list(bars1) + list(bars2):
    axes[1].text(
        bar.get_x() + bar.get_width() / 2,
        bar.get_height() + 30,
        str(int(bar.get_height())),
        ha='center', fontsize=9, fontweight='bold'
    )

axes[1].set_xticks(x)
axes[1].set_xticklabels(order)
axes[1].set_xlabel('Age Group', fontsize=12)
axes[1].set_ylabel('Count', fontsize=12)
axes[1].set_title('Age Group Distribution — Test Set', fontsize=13, fontweight='bold')
axes[1].legend(fontsize=11)
axes[1].set_facecolor('#f9f9f9')

plt.suptitle('Test Set Age Distribution (DeepFace Estimated)',
             fontsize=14, fontweight='bold', y=1.02)
plt.tight_layout()
plt.savefig(OUTPUT, dpi=150, bbox_inches='tight', facecolor='white')
print(f"\nSaved to {OUTPUT}")
