"""
plot_pixel_intensity.py — Pixel Intensity vs Error Rate Plots
=============================================================
Visualises the relationship between image brightness/contrast and
model error rates for both EfficientNet-B4 and XceptionNet.

How it works:
    1. Loads pixel statistics from pixel_intensity_results.csv
    2. Groups images into brightness/contrast bins
    3. Computes error rate per bin
    4. Plots error rate curves for both models

Interpretation:
    - If error rate increases at extreme brightness values (very dark or
      very bright images), this confirms that atypical illumination
      contributes to model failures — supporting the Grad-CAM findings.
    - High contrast (high std_brightness) images with harsh shadows
      may also show elevated error rates.

Usage:
    python plot_pixel_intensity.py

Prerequisites:
    - ~/results/pixel_intensity_results.csv must exist
      (generated by pixel_intensity_analysis.py)

Outputs:
    - ~/results/pixel_intensity_plot.png

"""

import os
import csv
import numpy as np

import matplotlib
matplotlib.use('Agg')
import matplotlib.pyplot as plt

# ─────────────────────────────────────────
# PATHS
# ─────────────────────────────────────────
INPUT  = os.path.expanduser('~/results/pixel_intensity_results.csv')
OUTPUT = os.path.expanduser('~/results/pixel_intensity_plot.png')

os.makedirs(os.path.expanduser('~/results'), exist_ok=True)

# ─────────────────────────────────────────
# LOAD DATA
# ─────────────────────────────────────────
print("Loading pixel intensity data...")

brightness, contrast, eff_errors, xcp_errors = [], [], [], []

with open(INPUT) as f:
    for row in csv.DictReader(f):
        brightness.append(float(row['mean_brightness']))
        contrast.append(float(row['std_brightness']))
        eff_errors.append(int(row['eff_error']))
        xcp_errors.append(int(row['xcp_error']))

brightness  = np.array(brightness)
contrast    = np.array(contrast)
eff_errors  = np.array(eff_errors)
xcp_errors  = np.array(xcp_errors)

print(f"Loaded {len(brightness):,} images.")

# ─────────────────────────────────────────
# BIN ANALYSIS
# ─────────────────────────────────────────
# Divide brightness range into 20 equal bins
# Only include bins with >50 images for statistical reliability

def compute_binned_error_rates(values, errors, n_bins=20, min_count=50):
    """
    Compute error rate per bin of a continuous variable.

    Args:
        values: array of continuous values (e.g. brightness)
        errors: binary array (1=error, 0=correct)
        n_bins: number of bins to divide the range into
        min_count: minimum images per bin for inclusion

    Returns:
        bin_centers: midpoint of each bin
        error_rates: error rate (%) for each bin
    """
    bins     = np.linspace(values.min(), values.max(), n_bins)
    bin_idx  = np.digitize(values, bins)

    bin_centers, error_rates = [], []
    for i in range(1, len(bins)):
        mask = bin_idx == i
        if mask.sum() >= min_count:
            error_rates.append(errors[mask].mean() * 100)
            bin_centers.append(bins[i-1])

    return bin_centers, error_rates

# Brightness bins
bright_centers, eff_bright_rates = compute_binned_error_rates(brightness, eff_errors)
_,              xcp_bright_rates = compute_binned_error_rates(brightness, xcp_errors)

# Contrast bins
contrast_centers, eff_contrast_rates = compute_binned_error_rates(contrast, eff_errors)
_,                xcp_contrast_rates = compute_binned_error_rates(contrast, xcp_errors)

# ─────────────────────────────────────────
# PLOT
# ─────────────────────────────────────────
fig, axes = plt.subplots(1, 2, figsize=(14, 5))
fig.patch.set_facecolor('white')

# ── Panel 1: Error rate vs brightness ──
axes[0].plot(bright_centers, eff_bright_rates,
             color='#2a9d8f', lw=2.5, marker='o', label='EfficientNet-B4')
axes[0].plot(bright_centers, xcp_bright_rates,
             color='#e76f51', lw=2.5, marker='o', label='XceptionNet')
axes[0].set_xlabel('Mean Brightness (0-255)', fontsize=12)
axes[0].set_ylabel('Error Rate (%)', fontsize=12)
axes[0].set_title('Error Rate vs Image Brightness', fontsize=13, fontweight='bold')
axes[0].legend(fontsize=11)
axes[0].set_facecolor('#f9f9f9')

# ── Panel 2: Error rate vs contrast ──
axes[1].plot(contrast_centers, eff_contrast_rates,
             color='#2a9d8f', lw=2.5, marker='o', label='EfficientNet-B4')
axes[1].plot(contrast_centers, xcp_contrast_rates,
             color='#e76f51', lw=2.5, marker='o', label='XceptionNet')
axes[1].set_xlabel('Contrast — Std of Brightness', fontsize=12)
axes[1].set_ylabel('Error Rate (%)', fontsize=12)
axes[1].set_title('Error Rate vs Image Contrast', fontsize=13, fontweight='bold')
axes[1].legend(fontsize=11)
axes[1].set_facecolor('#f9f9f9')

plt.suptitle('Pixel Intensity Analysis — Error Rate by Image Properties',
             fontsize=14, fontweight='bold', y=1.02)
plt.tight_layout()
plt.savefig(OUTPUT, dpi=150, bbox_inches='tight', facecolor='white')
print(f"Saved to {OUTPUT}")
